FROM golang:latest

RUN apt-get update

# Set necessary environmet variables needed for our image
ENV GO111MODULE=auto \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

# Move to working directory /build
WORKDIR /build

# Copy and download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy the code into the container
COPY . .

# Run unit tests before building
RUN go test -v ./Tests/cake_test.go

# Build the application
RUN go build -o main main.go

# Move to /dist directory as the place for resulting binary folder
WORKDIR /dist

# Copy binary from build to main folder
RUN cp /build/main .

RUN touch .env

EXPOSE 7890

# Run executable
CMD ["sh", "-c", "./main"]